### ISSUE TITLE
2&3 player modes don't work

### ISSUE THREAD

**Issue by bmoren** [bmoren/hft-bikez#10]
when I started adding the powerups, something went a little haywire with the 2player mode, the white human starts out with its head ontop of itself resulting in instant death. in 3 player mode, there are only 2 players.

**Comment by mediaupstream** [comment]
maybe it's a feature? if you are player 2 you just die right away :skull:

**Comment by mediaupstream** [comment]
When I added the AI stuff I made AI the default so you need to manually set the player's `ai` value to false if you want it to be controllable.

I think there's a bug with my AI code where sometimes the AI player will make a move that looks like his head is ontop of himself and he dies right away, it's pretty funny so I never fixed it :)

Also I just added a global "sound_on" variable so you can turn sounds off while developing, if you wanted to :+1:

**Comment by bmoren** [comment]
I'm getting a thing where the AI is off for the first 2 players, so human controlled. and the white player is always starting with its head ontop of itself. If I choose 3 player mode, there are only 2 players rendered to the screen.

![screen shot 2015-03-22 at 9 48 02 am](https://cloud.githubusercontent.com/assets/1385996/6769844/927c3384-d078-11e4-826b-e17e26f1f9ac.png)

**Comment by mediaupstream** [comment]
lmk when u wanna get together this week   

-D

**Comment by mediaupstream** [comment]
lmk when you want to meetup this week, I can show you what I think is going on in the code :8ball:
