### ISSUE TITLE
Color array

### ISSUE THREAD

**Issue by bmoren** [bmoren/hft-bikez#28]

**Comment by bmoren** [comment]
should the color array be multi dimensional so that it can contain both the rgb and the inverse rgb so we don't have to use the inverse RGB functions?

**Comment by jkim5** [comment]
I'm not sure color array is necessary anymore now that we have to ready...go screens where players find themselves. Once players have their eyes on their bike, they probably won't lose track of it even if another player is the same color. Something to test.
