### ISSUE TITLE
new names

### ISSUE THREAD

**Issue by bmoren** [bmoren/hft-bikez#44]
superCollider 

game of collisions
superWormz

**Comment by jkim5** [comment]
Something relating to Cyclotrons (a kind of super collider) - https://en.wikipedia.org/wiki/List_of_accelerators_in_particle_physics#Cyclotrons

Cool collider names - 

https://en.wikipedia.org/wiki/TRIUMF
https://en.wikipedia.org/wiki/RIKEN
